apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinc
  labels:
    app: spring-petclinc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-petclinc
  template:
    metadata:
      labels:
        app: spring-petclinc
    spec:
      containers:
      - name: spring-petclinc
        image: rathaiah/spring-petclinic:5
        ports:
        - containerPort: 8080
